airportData = [

["Logan County Airport - Lincoln, Illinois, United States","AAA"],
["Anaa Airport - Anaa, Tuamotu Island, French Polynesia","AAA"],
["Arrabury Airport - Arrabury, Queensland, Australia","AAB"],
["El Arish International Airport - El Arish, Egypt","AAC"],
["Rabah Bitat Airport (Les Salines Airport) - Annaba, Algeria","AAE"],
["Apalachicola Municipal Airport - Apalachicola, Florida, United States","AAF"],
["Arapoti Airport - Arapoti, Parana, Brazil","AAG"],
["Merzbruck Airport - Aachen, Germany","AAH"],
["Aranuka Airport - Aranuka, Kiribati","AAK"],
["Aalborg Airport - Aalborg, Denmark","AAL"],
["Mala Mala Airport - Mala Mala, South Africa","AAM"],
["Al Ain International Airport - Al Ain, United Arab Emirates","AAN"],
["Colonel James Jabara Airport - Wichita, Kansas, United States","AAO"],
["Anaco Airport - Anaco, Venezuela","AAO"],
["Vityazevo Airport - Anapa, Russia","AAQ"],
["Aarhus Airport - Aarhus, Denmark","AAR"],
["Taylor County Airport - Campbellsville, Kentucky, United States","AAS"],
["Alturas Municipal Airport - Alturas, California, United States","AAT"],
["Altay Airport - Altay, Xinjiang, China","AAT"],
["Asau Airport - Asau, Samoa","AAU"],
["Allah Valley Airport - Allah Valley, Mindanao, Philippines","AAV"],
["Araxa Airport (Aeroporto Araxa) - Araxa, Minas Gerais, Brazil","AAX"],
["Al Ghaydah Airport - Al Ghaydah, Yemen","AAY"],
["King Abdul-Aziz Naval Base - Jubail, Saudi Arabia","AAZ"],
["Abakan Airport - Abakan, Russia","ABA"],
["RAF Abingdon - Abingdon, England, United Kingdom","ABB"],
["Los Llanos Airport - Albacete, Spain","ABC"],
["Abadan Airport - Abadan, Iran","ABD"],
["Lehigh Valley International Airport - Allentown, Pennsylvania, United States","ABE"],
["Abaiang Atoll Airport - Abaiang, Kiribati","ABF"],
["Alpha Airport - Alpha, Queensland, Australia","ABH"],
["Abilene Regional Airport - Abilene, Texas, United States","ABI"],
["Port Bouet Airport (Felix Houphouet Boigny International Airport) - Abidjan, Ivory Coast","ABJ"],
["Kabri Dar Airport - Kabri Dar (or Kabre Dare), Ethiopia","ABK"],
["Bamaga Injinoo Airport - Bamaga, Queensland, Australia","ABM"],
["Aboisso Airport - Aboisso, Ivory Coast","ABO"],
["Albuquerque International Sunport - Albuquerque, New Mexico, United States","ABQ"],
["Aberdeen Regional Airport - Aberdeen, South Dakota, United States","ABR"],
["Abu Simbel Airport - Abu Simbel, Egypt","ABS"],
["Al-Aqiq Airport - Al-Baha, Saudi Arabia","ABT"],
["Haliwen Airport - Atambua, Indonesia","ABU"],
["Nnamdi Azikiwe International Airport - Abuja, Nigeria","ABV"],
["Albury Airport - Albury, New South Wales, Australia","ABX"],
["Southwest Georgia Regional Airport - Albany, Georgia, United States","ABY"],
["Dyce Airport - Aberdeen, Scotland, United Kingdom","ABZ"],
["General Juan N. Alvarez International Airport - Acapulco, Mexico","ACA"],
["Antrim County Airport - Bellaire, Michigan, United States","ACB"],
["Kotoka International Airport - Accra, Ghana","ACC"],
["Acandi Airport - Acandi, Colombia","ACD"],
["Arrecife Airport - Lanzarote, Canary Islands, Spain","ACE"],
["St. Gallen Altenrhein Airport - Altenrhein, Switzerland","ACH"],
["Alderney Airport - The Blaye, Alderney, Channel Islands, United Kingdom","ACI"],
["Souther Field - Americus, Georgia, United States","ACJ"],
["Nantucket Memorial Airport - Nantucket, Massachusetts, United States","ACK"],
["Cesar Airport - Aguaclara, Colombia","ACL"],
["Ciudad Acuna International Airport - Ciudad Acuna, Mexico","ACN"],
["Ascona Airport - Ascona, Switzerland","ACO"],
["Allen Parish Airport - Oakdale, Louisiana, United States","ACP"],
["Waseca Municipal Airport - Waseca, Minnesota, United States","ACQ"],
["Araracuara Airport - Araracuara, Colombia","ACR"],
["Waco Regional Airport - Waco, Texas, United States","ACT"],
["Arcata/Eureka Airport - McKinleyville, California (near Arcata and Eureka), United States","ACV"],
["Atlantic City International Airport - Atlantic City, New Jersey, United States","ACY"],
["Henderson Field - Wallace, North Carolina, United States","ACZ"],
["Sakirpasa Airport - Adana, Turkey","ADA"],
["Adnan Menderes Airport - Izmir, Turkey","ADB"],
["Andakombe Airport - Andakombe, Papua New Guinea","ADC"],
["Bole International Airport - Addis Ababa, Ethiopia","ADD"],
["Aden International Airport - Aden, Yemen","ADE"],
["Incirlik Air Base - Adana, Turkey","ADF"],
["Lenawee County Airport - Adrian, Michigan, United States","ADG"],
["Ada Municipal Airport - Ada, Oklahoma, United States","ADH"],
["Aldan Airport - Aldan, Russia","ADH"],
["Arandis Airport - Arandis/Swakopmund, Namibia","ADI"],
["Marka International Airport - Amman, Jordan","ADJ"],
["Adak Island Airport - Adak Island, Alaska, United States","ADK"],
["Adelaide International Airport - Adelaide, South Australia, Australia","ADL"],
["Ardmore Municipal Airport - Ardmore, Oklahoma, United States","ADM"],
["Andes Airport - Andes, Colombia","ADN"],
["Andamooka Airport - Andamooka, South Australia, Australia","ADO"],
["Anuradhapura Airport - Anuradhapura, Sri Lanka","ADP"],
["Kodiak Airport - Kodiak, Alaska, United States","ADQ"],
["Addison Airport - Dallas, Texas, United States","ADS"],
["Atwood-Rawlins County Airport - Atwood, Kansas, United States","ADT"],
["Audubon County Airport - Audubon, Iowa, United States","ADU"],
["Ardabil Airport - Ardabil, Iran","ADU"],
["Andrews AFB - Camp Springs, Maryland, United States","ADW"],
["RAF Leuchars - St Andrews, Scotland, United Kingdom","ADX"],
["Augsburg Airport - Augsburg, Germany","AGB"],
["Allegheny County Airport - Pittsburgh, Pennsylvania, United States","AGC"],
["Wangerooge Airport (Wangerooger Flughafen) - Wangerooge, Germany","AGE"],
["La Garenne Airport - Agen, France","AGF"],
["Angelholm/Helsingborg Airport (former ICAO code: ESDB) - Helsingborg, Sweden","AGH"],
["Wageningen Airport - Wageningen, Suriname","AGI"],
["Aguni Airport - Aguni, Japan","AGJ"],
["Angmagssalik Airport - Tasiilaq, Greenland","AGM"],
["Angoon Seaplane Base - Angoon, Alaska, United States","AGN"],
["Magnolia Municipal Airport - Magnolia, Arkansas, United States","AGO"],
["Pablo Ruiz Picasso Airport - Malaga, Spain","AGP"],
["Agrinion Airport - Agrinion, Greece","AGQ"],
["MacDill AFB Aux. Field - Avon Park, Florida, United States","AGR"],
["Kheria Airport - Agra, India","AGR"],
["Augusta Regional Airport at Bush Field - Augusta, Georgia, United States","AGS"],
["Guarani International Airport (Alejo Garcia Airport) - Ciudad del Este, Paraguay","AGT"],
["Lic. Jesus Teran Peredo International Airport - Aguascalientes, Mexico","AGU"],
["Oswaldo Guevara Mujica Airport - Acarigua, Venezuela","AGV"],
["Agatti Island Airport - Agatti Island, India","AGX"],
["Wagner Municipal Airport - Wagner, South Dakota, United States","AGZ"],
["Aggeneys Airport - Aggeneys, South Africa","AGZ"],
["Alliance Municipal Airport - Alliance, Nebraska, United States","AIA"],
["Anderson Municipal Airport (Darlington Field) - Anderson, Indiana, United States","AID"],
["Assis Airport - Assis, Sao Paulo, Brazil","AIF"],
["Langlade County Airport - Antigo, Wisconsin, United States","AIG"],
["Yalinga Airport - Yalinga, Central African Republic","AIG"],
["Ali-Sabieh Airport - Ali-Sabieh, Djibouti","AII"],
["Aiken Municipal Airport - Aiken, South Carolina, United States","AIK"],
["Wainwright AS - Fort Wainwright, Alaska, United States","AIN"],
["Atlantic Municipal Airport - Atlantic, Iowa, United States","AIO"],
["Arorae Island Airport - Arorae Island, Kiribati","AIS"],
["Aitkin Municipal Airport (Steve Kurtz Field) - Aitkin, Minnesota, United States","AIT"],
["Aitutaki Island Airport - Aitutaki, Cook Islands","AIT"],
["Atiu Island Airport - Atiu Island, Cook Islands","AIU"],
["George Downer Airport - Aliceville, Alabama, United States","AIV"],
["Bogota, Colombia - Eldorado","BOG"],
["Panama City, Panama - Tocumen International Airport","PTY"]
]
 